name: Nwt Search
on:
  push:
    branches:
      - master
jobs:
  build_assets:
    if: github.event_name  == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: build web assets
        env:
          TYPESENSE_SEARCH_ONLY_API_KEY: ${{ secrets.TYPESENSE_SEARCH_ONLY_API_KEY }}
          TYPESENSE_HOST: api.nwt-search.live
          TYPESENSE_PORT: 443
          TYPESENSE_PROTOCOL: https
          TYPESENSE_COLLECTION_NAME: contents
        run: |
          echo $TYPESENSE_SEARCH_ONLY_API_KEY
          npm ci
          npm run build
  release:
    if: github.event_name == 'push'
    needs: [ build_assets ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v0.4.1
        with:
          credentials_json: "${{ secrets.GCS_IAM_SERVICE_ACCOUNT }}"
      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Deploy on production
        if: github.ref == 'refs/heads/master'
        run: |
          npm run deploy